# Generated by Django 3.1.8 on 2021-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="mappings",
            field=models.JSONField(default=None, null=True),
        ),
    ]
