# Generated by Django 3.1.8 on 2021-07-08 14:16

from django.db import migrations, models

import cuid


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                ("id", models.TextField(default=cuid.cuid, editable=False, primary_key=True, serialize=False)),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
