# Generated by Django 3.1.8 on 2021-08-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0002_batch_mappings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="resources",
            new_name="resource_ids",
        ),
    ]
