# Generated by Django 3.1.8 on 2021-08-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0005_remove_error_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="error",
            name="exception",
        ),
        migrations.RemoveField(
            model_name="error",
            name="message",
        ),
    ]
