# Generated by Django 3.1.12 on 2021-08-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0006_remove_error_exception"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="resource_ids",
        ),
    ]
