# Generated by Django 3.1.12 on 2021-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0008_column_ordering"),
        ("river", "0007_remove_batch_resource_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="resources",
            field=models.ManyToManyField(to="pyrog.Resource"),
        ),
    ]
