# Generated by Django 3.1.12 on 2021-10-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0008_batch_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="progressions",
            field=models.JSONField(default=None, null=True),
        ),
    ]
