# Generated by Django 3.1.12 on 2021-10-26 09:49

import django.db.models.deletion
from django.db import migrations, models

import cuid


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0008_batch_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progression",
            fields=[
                ("id", models.TextField(default=cuid.cuid, editable=False, primary_key=True, serialize=False)),
                ("extracted", models.IntegerField(null=True)),
                ("loaded", models.IntegerField(null=True)),
                ("failed", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="progressions", to="river.batch"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="progressions", to="pyrog.resource"
                    ),
                ),
            ],
        ),
    ]
