source:
  model: "POSTGRES"
  host: "localhost"
  port: 5431
  database: "mimic"
  login: "mimicuser"
  password: "mimicuser"

fhirstore:
  host: "localhost"
  port: 27017
  database: "fhirstore"
  user: null
  password: null

graphql:
  server: "https://graphql.pyrog.staging.arkhn.org/"
  token: "<token>"

fhir-api:
  url: "https://fhir.staging.arkhn.org/api"

logging:
  filename: fhirpipe.log

