sql:
  default: "postgres"
  postgres:
    lib: "psycopg2"
    args: []
    kwargs:
      host: mimic
      port: 5432
      database: "mimic"
      user: "mimicuser"
      password: "mimicuser"
    oracle:
      lib: "cx_Oracle"
      args: ["user/password@database"]
      kwargs: {}
fhirstore:
  host: "mongo"
  port: 27017
  database: "fhirstore"
  user: null
  password: null

graphql:
  server: "http://pyrog-server:4000"
  token: "<token>"

fhir-api:
  url: http://fhir:2000
