version: "3.7"

services:
  benchmark:
    image: benchmark
    build: benchmark

  extractor:
    image: river
    build: .
    command: extractor
    depends_on:
      - kafka
    restart: on-failure
    environment:
      - ENV=dev
      - SECRET_KEY=whatever
      - LOG_LEVEL=DEBUG
      - REDIS_MAPPINGS_HOST=river-redis
      - REDIS_MAPPINGS_PORT=6379
      - REDIS_MAPPINGS_DB=1
      - REDIS_COUNTER_HOST=river-redis
      - REDIS_COUNTER_PORT=6379
      - REDIS_COUNTER_DB=2

  transformer:
    image: river
    build: .
    command: transformer
    depends_on:
      - kafka
    restart: on-failure
    environment:
      - ENV=dev
      - SECRET_KEY=whatever
      - LOG_LEVEL=DEBUG
      - REDIS_MAPPINGS_HOST=river-redis
      - REDIS_MAPPINGS_PORT=6379
      - REDIS_MAPPINGS_DB=1

  loader:
    image: river
    build: .
    command: loader
    depends_on:
      - kafka
    restart: on-failure
    environment:
      - ENV=dev
      - SECRET_KEY=whatever
      - LOG_LEVEL=DEBUG
      - FHIRSTORE_USER=arkhn
      - FHIRSTORE_PASSWORD=5gBwjTYR4DHSbzaUwVNX43DbTn
      - REDIS_REFERENCES_HOST=river-redis
      - REDIS_REFERENCES_PORT=6379
      - REDIS_REFERENCES_DB=0
      - REDIS_MAPPINGS_HOST=river-redis
      - REDIS_MAPPINGS_PORT=6379
      - REDIS_MAPPINGS_DB=1
      - REDIS_COUNTER_HOST=river-redis
      - REDIS_COUNTER_PORT=6379
      - REDIS_COUNTER_DB=2

  api:
    build: api
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - PORT=3000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXTRACTOR_URL=http://extractor:3001
      - TRANSFORMER_URL=http://transformer:3002
      - LOADER_URL=http://loader:3003
      - PYROG_API_URL=http://pyrog-server:1000
      - FHIR_API_URL=http://fhir-api:2000
      - REDIS_MAPPINGS_HOST=river-redis
      - REDIS_MAPPINGS_PORT=6379
      - REDIS_MAPPINGS_DB=1
      - REDIS_COUNTER_HOST=river-redis
      - REDIS_COUNTER_PORT=6379
      - REDIS_COUNTER_DB=2

  zookeeper:
    image: zookeeper:3.4.10
    restart: on-failure

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    restart: on-failure
    # This port mapping is required by the containerized kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9993 -Dcom.sun.management.jmxremote.port=9993
      - JMX_PORT=9993
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-jmx-exporter:
    image: sscaling/jmx-prometheus-exporter
    volumes:
      - ./monitoring/jmx_exporter.yml:/opt/jmx_exporter/config.yml

  river-redis:
    image: redis:6.0.7
    restart: on-failure
    command: --loglevel verbose

  prometheus:
    image: prom/prometheus:v2.23.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

networks:
  default:
    external:
      name: arkhn_network
