version: "3.7"
services:
  mimic:
    image: arkhn/mimic:latest
    container_name: mimic
    env_file: .env
    restart: always
    environment:
      POSTGRES_USER: mimicuser
      POSTGRES_PASSWORD: mimicuser
      POSTGRES_DB: mimic
      POSTGRES_HOST: mimic
      POSTGRES_PORT: 5432
    volumes:
      - mimic-db:/var/lib/postgresql/data
    ports:
      - 5431:5432

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fhirstore
    ports:
      - 27017:27017
    volumes:
      - fhirstore-db:/data/db

  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - ~/Documents/Arkhn/fhir-river/test/sftp/host/upload/:/home/arkhn/upload/
    ports:
      - "2222:22"
    command: arkhn:arkhnpwd:1001

  zookeeper:
    image: "zookeeper:3.4.10"
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    expose:
      - "2181"

  kafka:
    image: "wurstmeister/kafka:0.10.2.1"
    restart: always
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DELETE_TOPIC_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  kafka_connect:
#    image: confluentinc/cp-kafka-connect:latest
#    restart: always
#    container_name: kafka_connect
#    ports:
#      - "8083:8083"
#    depends_on:
#      - kafka
#    volumes:
#      - ./kafka_connect_connectors/plugins/confluentinc-kafka-connect-sftp-1.0.4/:/usr/share/java/kafka-connect-sftp/
#    environment:
#      CONNECT_CLASS_PATH: "/usr/share/java/kafka-connect-jdbc/,/usr/share/java/kafka-connect-sftp/"
#      CONNECT_PLUGIN_PATH: /usr/share/java/
#      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
#      CONNECT_GROUP_ID: source-kafka-connect
#      CONNECT_CONFIG_STORAGE_TOPIC: default.config
#      CONNECT_STATUS_STORAGE_TOPIC: default.status
#      CONNECT_OFFSET_STORAGE_TOPIC: default.offset
#      CONNECT_STATUS_STORAGE_PARTITIONS: 1
#      CONNECT_OFFSET_STORAGE_PARTITIONS: 1
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
#      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_REST_PORT: 8083
#      CONNECT_REST_ADVERTISED_HOST_NAME: docker
#      CONNECT_SCHEMAS_ENABLE: "false"
#      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
#      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
#      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181

  fhir_transformer:
    build:
      context: fhir_transformer/
    container_name: fhir_transformer
    image: arkhn/fhir-transformer:latest
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  fhir_loader:
    build:
      context: fhir_loader/
    container_name: fhir_loader
    image: arkhn/fhir-loader:latest
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  fhir_extractor:
    build:
      context: fhir_extractor/
    container_name: fhir_extractor
    image: arkhn/fhir-extractor:latest
    restart: always
    depends_on:
      - kafka
    environment:
      API_URL: "https://pyrog.arkhn.org/api"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_USER: mimicuser
      POSTGRES_PASSWORD: mimicuser
      POSTGRES_DB: mimic
      POSTGRES_HOST: mimic
      POSTGRES_PORT: 5432
    expose:
      - "5000"
    ports:
      - "5000:5000"



volumes:
  mimic-db:
    name: mimic-db
  fhirstore-db:
