version: "3.7"

services:
  hapi-loader:
    image: arkhn/hapi-loader:latest
    build: .
    restart: on-failure
    depends_on:
      - elasticsearch
    volumes:
      - ./application.docker.yaml:/app/application.yaml

  zookeeper:
    image: zookeeper:3.4.10
    restart: on-failure
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    restart: on-failure
    # This port mapping is required by the containerized kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_LISTENERS=INSIDE://kafka:9093,OUTSIDE://:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # The following option can be used in local, but should not be used in production.
      # It constrains the initial/maximum virtual memory allocated for the JVM.
      # - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=deadbeefdeadbeef
      - POSTGRES_DB=test-hapi-db
    ports:
      - 5432:5432
    volumes:
      - hapi-pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf

  elasticsearch:
    image: elasticsearch:7.9.3
    restart: always
    environment:
      - ELASTIC_PASSWORD=SomePassword
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    volumes:
      - hapi-eldata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=SomePassword
    depends_on:
      - elasticsearch

  fluentd:
    image: arkhn/fluentd:latest
    ports:
      - 24224:24224
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf

volumes:
  hapi-pgdata:
  hapi-eldata:
