global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka-jmx-exporter:5556"
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080"
  - job_name: "system"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "collect-extractor"
    scrape_interval: 5s
    static_configs:
      - targets: ["extractor:8001"]
  - job_name: "collect-transformer"
    scrape_interval: 5s
    static_configs:
      - targets: ["transformer:8001"]
  - job_name: "collect-loader"
    scrape_interval: 5s
    static_configs:
      - targets: ["loader:8001"]
