{
 "title": "River dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Extract time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(time_extractor_extract_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Load time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "increase(time_load_bucket[5m])", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Transform time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(time_transformer_transform_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create document time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(time_create_fhir_document_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(count_load_total[1m])" }
   ]
  }
 ]
}