{
 "title": "River dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average times extractor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_extractor_extract_sum[1m]) / rate(time_extractor_extract_count[1m])"
    },
    {
     "expr": "rate(time_extractor_build_query_sum[1m]) / rate(time_extractor_build_query_count[1m])"
    },
    {
     "expr": "rate(time_extractor_run_query_sum[1m]) / rate(time_extractor_run_query_count[1m])"
    },
    {
     "expr": "rate(time_extractor_split_sum[1m]) / rate(time_extractor_split_count[1m])"
    }
   ]
  },
  {
   "title": "Average times transformer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_transformer_transform_sum[1m]) / rate(time_transformer_transform_count[1m])"
    },
    {
     "expr": "rate(time_create_fhir_document_sum[1m]) / rate(time_create_fhir_document_count[1m])"
    }
   ]
  },
  {
   "title": "Average times loader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_load_sum[1m]) / rate(time_load_count[1m])"
    }
   ]
  },
  {
   "title": "Extract time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(time_extractor_extract_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Load time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "increase(time_load_bucket[5m])", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Transform time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(time_transformer_transform_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create document time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(time_create_fhir_document_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(count_load_total[1m])" }
   ]
  }
 ]
}