# Generated by Django 3.1.2 on 2021-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("path", models.TextField()),
                ("slice_name", models.TextField(blank=True, default="")),
                ("definition_id", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("table", models.TextField()),
                ("column", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("host", models.TextField()),
                ("port", models.IntegerField()),
                ("database", models.TextField()),
                ("login", models.TextField()),
                ("password", models.TextField()),
                (
                    "model",
                    models.TextField(
                        choices=[
                            ("MSSQL", "Mssql"),
                            ("POSTGRES", "Postgresql"),
                            ("ORACLE", "Oracle"),
                            ("SQLLITE", "Sqllite"),
                        ]
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("schema", models.JSONField(blank=True, null=True)),
                ("credential", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pyrog.credential")),
            ],
            options={
                "unique_together": {("name", "credential")},
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("version", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="pyrog.template"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "template")},
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, default="")),
                ("primary_key_table", models.TextField()),
                ("primary_key_column", models.TextField()),
                ("definition_id", models.TextField()),
                ("logical_reference", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_key_owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pyrog.owner"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="pyrog.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Join",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to="pyrog.column",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputGroup",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("merging_script", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_groups",
                        to="pyrog.attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Input",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("script", models.TextField(blank=True, default="")),
                ("concept_map_id", models.TextField(blank=True, default="")),
                ("static_value", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="pyrog.inputgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "relation",
                    models.TextField(
                        choices=[
                            ("=", "Equal"),
                            ("<>", "Not Equal"),
                            ("IN", "In"),
                            (">", "Greater"),
                            (">=", "Greater Or Equal"),
                            ("<", "Lesser"),
                            ("<=", "Lesser Or Equal"),
                        ]
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pyrog.resource"
                    ),
                ),
                ("sql_column", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="pyrog.column")),
            ],
        ),
        migrations.AddField(
            model_name="credential",
            name="source",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="pyrog.source"),
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("action", models.TextField(choices=[("INCLUDE", "Include"), ("EXCLUDE", "Exclude")])),
                ("value", models.TextField(blank=True, default="")),
                (
                    "relation",
                    models.TextField(
                        choices=[
                            ("EQ", "Equal"),
                            ("GT", "Greater"),
                            ("GE", "Greater Or Equal"),
                            ("LT", "Lesser"),
                            ("LE", "Lesser Or Equal"),
                            ("NOTNULL", "Notnull"),
                            ("NULL", "Null"),
                        ],
                        default="EQ",
                    ),
                ),
                (
                    "column",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pyrog.column"
                    ),
                ),
                ("input_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pyrog.inputgroup")),
            ],
        ),
        migrations.AddField(
            model_name="column",
            name="input",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pyrog.input"
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="join",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="pyrog.join",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="pyrog.owner",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="pyrog.resource",
            ),
        ),
    ]
