# Generated by Django 3.1.2 on 2021-02-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="source",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="source",
            name="template",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
