# Generated by Django 3.1.2 on 2021-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0002_unique_source_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="source",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="source",
            name="template",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
