# Generated by Django 3.1.8 on 2021-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0004_drop_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="static_value",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
