# Generated by Django 3.1.12 on 2021-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0008_column_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="definition",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
