# Generated by Django 3.1.12 on 2021-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0009_move_column_fk_on_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="definition",
            field=models.JSONField(null=True, blank=True, default=None),
            preserve_default=False,
        ),
    ]
