# Generated by Django 3.1.12 on 2021-09-01 13:53

import django.db.models.deletion
from django.db import migrations, models

import cuid


def forwards_func(apps, schema_editor):
    Input = apps.get_model("pyrog", "Input")
    StaticInput = apps.get_model("pyrog", "StaticInput")
    SQLInput = apps.get_model("pyrog", "SQLInput")
    for input in Input.objects.all():
        if input.static_value:
            StaticInput.objects.create(input_group=input.input_group, value=input.static_value)
        elif input.column:
            SQLInput.objects.create(input_group=input.input_group, column=input.column)


def reverse_func(apps, schema_editor):
    Input = apps.get_model("pyrog", "Input")
    StaticInput = apps.get_model("pyrog", "StaticInput")
    SQLInput = apps.get_model("pyrog", "SQLInput")
    for static_input in StaticInput.objects.all():
        Input.objects.create(input_group=static_input.input_group, static_value=static_input.value)
    for sql_input in SQLInput.objects.all():
        Input.objects.create(input_group=sql_input.input_group, column=sql_input.column)


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0009_move_column_fk_on_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticInput",
            fields=[
                ("id", models.TextField(default=cuid.cuid, editable=False, primary_key=True, serialize=False)),
                ("value", models.TextField(blank=True, default=None, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_inputs",
                        to="pyrog.inputgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SQLInput",
            fields=[
                ("id", models.TextField(default=cuid.cuid, editable=False, primary_key=True, serialize=False)),
                ("script", models.TextField(blank=True, default="")),
                ("concept_map_id", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "column",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sql_input",
                        to="pyrog.column",
                    ),
                ),
                (
                    "input_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sql_inputs", to="pyrog.inputgroup"
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
