# Generated by Django 3.1.12 on 2021-09-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pyrog", "0011_split_static_and_sql_inputs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Input",
        ),
    ]
