# Generated by Django 3.1.13 on 2021-10-13 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyrog', '0014_split_join_left_right'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='column',
            options={},
        ),
        migrations.AlterField(
            model_name='resource',
            name='definition',
            field=models.JSONField(),
        ),
    ]
