# Generated by Django 3.1.13 on 2021-10-13 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyrog', '0015_rename_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceUser',
            new_name='ProjectUser',
        ),
    ]
