# Generated by Django 3.1.13 on 2021-10-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pyrog", "0016_rename_source_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="source",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="projectuser",
            old_name="source",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="source",
            new_name="project",
        ),
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                related_name="projects", through="pyrog.ProjectUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuser",
            unique_together={("user", "project")},
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_users", to="pyrog.project"
            ),
        ),
    ]
