{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Mean Messages In Rate  by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"MessagesInPerSec\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Mean Consumer Fetch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\", request=\"FetchConsumer\"}",
     "legendFormat": "Mean Consumer Fetch"
    }
   ]
  },
  {
   "title": "Total Messages In By Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}