{
 "title": "River dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Extract rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(count_extracted_instances_total[1m])",
     "legendFormat": "{{resource_type}}"
    },
    {}
   ]
  },
  {
   "title": "Transformer average time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_transformer_transform_data_sum[1m]) / rate(time_transformer_transform_data_count[1m])",
     "legendFormat": "transform dataframe"
    },
    {
     "expr": "rate(time_create_fhir_document_sum[1m]) / rate(time_create_fhir_document_count[1m])",
     "legendFormat": "build fhir document"
    }
   ]
  },
  {
   "title": "Extract count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_extracted_instances_total",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Load rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(count_load_total[1m])", "legendFormat": "{{resource_type}}" }
   ]
  },
  {
   "title": "Load count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_load_total", "legendFormat": "{{resource_type}}" }
   ]
  },
  {
   "title": "Failed Validations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_failed_validations_total", "legendFormat": "{{resource_type}}" }
   ]
  },
  {
   "title": "Average times extractor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_extractor_extract_sum[1m]) / rate(time_extractor_extract_count[1m])",
     "legendFormat": "total time extract"
    },
    {
     "expr": "rate(time_extractor_build_query_sum[1m]) / rate(time_extractor_build_query_count[1m])",
     "legendFormat": "build query"
    },
    {
     "expr": "rate(time_extractor_run_query_sum[1m]) / rate(time_extractor_run_query_count[1m])",
     "legendFormat": "run query"
    },
    {
     "expr": "rate(time_extractor_split_sum[1m]) / rate(time_extractor_split_count[1m])",
     "legendFormat": "split dataframe"
    }
   ]
  },
  {
   "title": "Average times loader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_load_sum[1m]) / rate(time_load_count[1m])",
     "legendFormat": "load to mongo"
    },
    {
     "expr": "rate(time_override_sum[1m]) / rate(time_override_count[1m])",
     "legendFormat": "override previous document"
    },
    {
     "expr": "rate(time_resolve_references_sum[1m]) / rate(time_resolve_references_count[1m])",
     "legendFormat": "resolve reference "
    }
   ]
  },
  {
   "title": "Reference resolver",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_bind_existing_reference_sum[1m]) / rate(time_bind_existing_reference_count[1m])",
     "legendFormat": "Bind to existing references"
    },
    {
     "expr": "rate(time_resolve_pending_references_sum[1m]) / rate(time_resolve_pending_references_count[1m])",
     "legendFormat": "Bind to pending references"
    }
   ]
  }
 ]
}