server:
  servlet:
    context-path: /hapi

spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:postgresql://postgres-hapi:5432/hapi"
    username: hapi
    password: hapi
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        search:
          enabled: false
  batch:
    job:
      enabled: false

hapi:
  fhir:
    server_address: http://jpaltime:8080/hapi/fhir
    admin_token: adminToken
    fhir_version: R4
    daoconfig_client_id_strategy: null
    bulk_export_enabled: false
    enforce_referential_integrity_on_delete: true
    enforce_referential_integrity_on_write: true
    allow_cascading_deletes: false
    allow_external_references: false
    allow_multiple_delete: false
    allow_inline_match_url_references: true
    enable_index_missing_fields: true
    use_consent_interceptor: false
    use_narrowing_interceptor: false

    tester:
      home:
        name: Local Tester
        server_address: http://jpaltime:8080/hapi/fhir
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
