name: app

on:
  push:
    paths:
      - "app/**"
    branches:
      - main
      - v4
    tags:
      - "v*"
  pull_request:
    paths:
      - "app/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: app
      - name: Run ESLint
        run: yarn lint
        working-directory: app
      - name: Run tests
        run: yarn test
        working-directory: app
  build-and-publish:
    needs: lint-and-test
    runs-on: ubuntu-18.04
    steps:
      - id: docker_meta
        name: Docker Metadata action
        uses: docker/metadata-action@v3.3.0
        with:
          images: arkhn/pyrog-app
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: app
          file: ./app/Dockerfile
          build-args: |
            VERSION_NAME=${{ steps.docker_meta.outputs.version }}
            VERSION_SHA=${GITHUB_SHA::8}
          platforms: linux/amd64
          # always push images to the hub
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
