name: fhir-river

on: [push]

jobs:
  unit-tests:
    name: Lint and test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install postgresql libpq-dev
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 analyzer extractor transformer loader api --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 analyzer extractor transformer loader api --count --max-complexity=10 --max-line-length=100 --statistics

      - name: Test with pytest
        env:
          PYROG_API_URL: http://test.com
        run: |
          python -m pytest -svv extractor/test transformer/test loader/test analyzer/test

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-18.04
    needs: docker-build
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install postgresql libpq-dev
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Pull docker images
        env:
          FHIR_API_TOKEN: ${{ secrets.FHIR_API_TOKEN }}
          AUTH_SIGNING_PUBLIC_KEY: ${{ secrets.AUTH_SIGNING_PUBLIC_KEY }}
          AUTH_SIGNING_PRIVATE_KEY: ${{ secrets.AUTH_SIGNING_PRIVATE_KEY }}
        run: |
          docker pull arkhn/river-api-go:$GITHUB_SHA
          docker pull arkhn/river-extractor:$GITHUB_SHA
          docker pull arkhn/river-transformer:$GITHUB_SHA
          docker pull arkhn/river-loader:$GITHUB_SHA
          docker-compose -f test/docker-compose.yml pull mimic mongo elasticsearch monstache zookeeper kafka fhir-api postgres redis pyrog-server

      - name: Tag images
        run: |
          docker tag arkhn/river-api-go:$GITHUB_SHA arkhn/river-api-go:latest
          docker tag arkhn/river-extractor:$GITHUB_SHA arkhn/river-extractor:latest
          docker tag arkhn/river-transformer:$GITHUB_SHA arkhn/river-transformer:latest
          docker tag arkhn/river-loader:$GITHUB_SHA arkhn/river-loader:latest

      - name: Integration tests with pytest
        env:
          FHIR_API_TOKEN: ${{ secrets.FHIR_API_TOKEN }}
          AUTH_SIGNING_PUBLIC_KEY: ${{ secrets.AUTH_SIGNING_PUBLIC_KEY }}
          AUTH_SIGNING_PRIVATE_KEY: ${{ secrets.AUTH_SIGNING_PRIVATE_KEY }}
          PYROG_API_URL: http://0.0.0.0:1000
          PYROG_LOGIN: admin@arkhn.com
          PYROG_PASSWORD: password
          KAFKA_BOOTSTRAP_SERVERS_EXTERNAL: "0.0.0.0:9092"
        run: |
          docker-compose -f test/docker-compose.yml up -d mongo mimic elasticsearch monstache
          docker-compose -f test/docker-compose.yml up -d kafka zookeeper
          docker-compose -f test/docker-compose.yml up -d fhir-api
          sleep 60
          MONGO_USERNAME=arkhn MONGO_PASSWORD=SuperSecurePassword2019 ./test/initiate_rep_set.sh
          docker exec fhir-api python3 scripts/upload_bundles.py fhir_bundles/resources.json fhir_bundles/conceptMaps.json
          docker restart fhir-api
          docker-compose -f test/docker-compose.yml up -d postgres redis pyrog-server
          sleep 30
          docker exec --env SUPERUSER_PASSWORD="password" pyrog-server yarn seed:superuser
          docker exec pyrog-server yarn seed:mapping /app/mapping.json
          docker exec pyrog-server yarn seed:credentials /app/credentials.json
          docker-compose -f test/docker-compose.yml up -d --build api extractor transformer loader
          sleep 15
          python -m pytest -svv test/test_batch.py

  publish:
    name: Publish docker images
    runs-on: ubuntu-18.04

    needs:
      - integration-tests
      - docker-build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1

      - name: Build images
        run: |
          docker build -f apigo/Dockerfile -t arkhn/river-api-go:$GITHUB_SHA -t arkhn/river-api-go:latest apigo
          docker build -f extractor/Dockerfile -t arkhn/river-extractor:$GITHUB_SHA -t arkhn/river-extractor:latest .
          docker build -f transformer/Dockerfile -t arkhn/river-transformer:$GITHUB_SHA -t arkhn/river-transformer:latest .
          docker build -f loader/Dockerfile -t arkhn/river-loader:$GITHUB_SHA -t arkhn/river-loader:latest .

      - name: Publish the latest tag to the docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push arkhn/river-api-go
          docker push arkhn/river-extractor
          docker push arkhn/river-transformer
          docker push arkhn/river-loader
