name: test

on:
  push:
    paths-ignore:
      - 'app/**'
    branches:
      - main
      - v4
  pull_request:
    paths-ignore:
      - 'app/**'

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: docker/login-action@v1
        name: login to arkhn registry
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: tests
        env:
          IMAGE_TAG: ${{ steps.docker-tag.outputs.river-version }}
          TEST_ORACLE_HOST: ${{ secrets.TEST_ORACLE_HOST }}
          TEST_ORACLE_PORT: ${{ secrets.TEST_ORACLE_PORT }}
          TEST_ORACLE_DB: ${{ secrets.TEST_ORACLE_DB }}
          TEST_ORACLE_LOGIN: ${{ secrets.TEST_ORACLE_LOGIN }}
          TEST_ORACLE_PASSWORD: ${{ secrets.TEST_ORACLE_PASSWORD }}
          TEST_MSSQL_HOST: ${{ secrets.TEST_MSSQL_HOST }}
          TEST_MSSQL_PORT: ${{ secrets.TEST_MSSQL_PORT }}
          TEST_MSSQL_DB: ${{ secrets.TEST_MSSQL_DB }}
          TEST_MSSQL_LOGIN: ${{ secrets.TEST_MSSQL_LOGIN }}
          TEST_MSSQL_PASSWORD: ${{ secrets.TEST_MSSQL_PASSWORD }}
        run: make unit-tests

  test-hapi:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '15'
      # runs the Maven `package` target in non-interactive mode to ensure
      # that the code builds, tests pass, and a package can be created.
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        working-directory: hapi-loader
